'use strict';
const $=s=>document.querySelector(s);
const MOD={'5k':'5K','10k':'10K',medio_maraton:'Media maratón',maraton:'Maratón',triatlon_sprint:'Triatlón sprint',triatlon_olimpico:'Triatlón olímpico',triatlon_media:'Triatlón 70.3',triatlon_larga:'Triatlón Ironman',hyrox:'HYROX',hibrida:'Híbridas',obstaculos:'Obstáculos'};
const GROUP={'5k':'run','10k':'run',medio_maraton:'run',maraton:'run',triatlon_sprint:'tri',triatlon_olimpico:'tri',triatlon_media:'tri',triatlon_larga:'tri',hyrox:'hyb',hibrida:'hyb',obstaculos:'ocr'};
const COLORS={run:'#E61E4D',tri:'#087F8C',hyb:'#7C3AED',ocr:'#A16207'};
const LEVEL={confirmada_web_oficial:'Web oficial',confirmada_organizacion:'Organización / agendas',fecha_estimada:'Fecha estimada',por_verificar:'Por verificar'};
const DIST={'5k':'5 km','10k':'10 km',medio_maraton:'21,097 km',maraton:'42,195 km',triatlon_sprint:'Sprint',triatlon_olimpico:'Olímpica',triatlon_media:'Media / 70.3',triatlon_larga:'Larga / Ironman',hyrox:'Carrera funcional',hibrida:'Carrera funcional',obstaculos:'Según evento'};
const ORDER=Object.keys(MOD);
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const safeUrl=s=>{try{const u=new URL(s);return /^https?:$/.test(u.protocol)?esc(u.href):''}catch{return ''}};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const fmt=d=>new Date(`${d}T12:00:00`).toLocaleDateString('es-ES',{day:'numeric',month:'short',year:'numeric'});
let carreras=[],view='buscar',visibleCount=30,map,layer,selected=null;
const state={text:'',mod:'',ccaa:'',province:'',month:'',level:'',sort:'fecha',visibleOnly:false};
function pass(r){return (!state.mod||r.modalidad===state.mod)&&(!state.text||norm(`${r.nombre} ${r.ciudad} ${r.provincia} ${MOD[r.modalidad]} ${DIST[r.modalidad]} ${r.fecha}`).includes(norm(state.text)))&&(!state.ccaa||r.ccaa===state.ccaa)&&(!state.province||r.provincia===state.province)&&(!state.month||r.fecha.startsWith(state.month))&&(!state.level||r.nivel_validacion===state.level)}
function filtered(){return carreras.filter(pass).sort((a,b)=>state.sort==='distancia'?(ORDER.indexOf(a.modalidad)-ORDER.indexOf(b.modalidad)||a.fecha.localeCompare(b.fecha)):state.sort==='nombre'?a.nombre.localeCompare(b.nombre):a.fecha.localeCompare(b.fecha))}
function badge(r){return `<span class="evidence ${esc(r.nivel_validacion)}">● ${esc(LEVEL[r.nivel_validacion]||'Sin validar')}${r.ultima_comprobacion?' · '+fmt(r.ultima_comprobacion):''}</span>`}
function card(r){const url=safeUrl(r.web_oficial);return `<article class="race-card" role="button" tabindex="0" data-id="${esc(r.id)}" aria-label="Ver ficha de ${esc(r.nombre)}"><div class="card-top"><span class="card-date">${fmt(r.fecha)}</span><span class="group-tag ${GROUP[r.modalidad]}">${esc(MOD[r.modalidad])}</span></div><h3>${esc(r.nombre)}</h3><p class="location">⌖ &nbsp;${esc([r.ciudad,r.provincia].filter(Boolean).join(', ')||'Ubicación no disponible')}</p><div class="card-bottom">${badge(r)}<span class="card-actions">${url?`<a class="card-official" href="${url}" target="_blank" rel="noopener noreferrer">Web oficial</a>`:''}<span class="arrow">Ver ficha</span></span></div></article>`}
function redraw(){const all=filtered();layer.clearLayers();for(const r of all){if(!r.lat||!r.lng)continue;L.circleMarker([r.lat,r.lng],{radius:6,color:'#fff',weight:1.5,fillColor:COLORS[GROUP[r.modalidad]],fillOpacity:.88}).bindTooltip(esc(r.nombre)).on('click',()=>openRace(r)).addTo(layer)}const shown=state.visibleOnly&&view==='mapa'?all.filter(r=>r.lat&&r.lng&&map.getBounds().contains([r.lat,r.lng])):all;$('#contador').innerHTML=`<b>${shown.length}</b> carreras${state.visibleOnly&&view==='mapa'?' en este mapa':''}`;$('#lista').innerHTML=shown.slice(0,visibleCount).map(card).join('')||'<div class="empty">No hay carreras con estos filtros. <button type="button" id="empty-clear">Limpiar filtros</button></div>';$('#ver-mas').hidden=shown.length<=visibleCount;$('#lista').querySelectorAll('.race-card').forEach(el=>{const r=carreras.find(x=>x.id===el.dataset.id);el.onclick=e=>{if(e.target.closest('a'))return;openRace(r)};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openRace(r)}}});const empty=$('#empty-clear');if(empty)empty.onclick=clear}
function closeRace(){selected=null;$('#ficha').hidden=true;document.querySelector('.modal-shade')?.remove();const url=new URL(location.href);url.searchParams.delete('carrera');history.replaceState(null,'',url)}
function openRace(r){if(!r)return;selected=r;const web=safeUrl(r.web_oficial),geo=r.lat&&r.lng?`https://www.google.com/maps/dir/?api=1&amp;destination=${encodeURIComponent(r.lat+','+r.lng)}`:'';$('#ficha').innerHTML=`<button class="ficha-cerrar" aria-label="Cerrar ficha">×</button><span class="group-tag ${GROUP[r.modalidad]}">${esc(MOD[r.modalidad])} · ${esc(DIST[r.modalidad])}</span><h2>${esc(r.nombre)}</h2><dl><dt>Fecha</dt><dd>${fmt(r.fecha)}${!r.fecha_confirmada?' · sin confirmar':''}</dd><dt>Lugar</dt><dd>${esc([r.ciudad,r.provincia,r.ccaa].filter(Boolean).join(', ')||'No disponible')}${r.ubicacion_aproximada?' · ubicación aproximada':''}</dd><dt>Precio</dt><dd>${esc(r.precio_texto||'No disponible')}</dd><dt>Validación</dt><dd>${badge(r)}</dd></dl><div class="detail-actions">${web?`<a class="primary" target="_blank" rel="noopener noreferrer" href="${web}">Web oficial</a>`:''}${geo?`<a class="secondary" target="_blank" rel="noopener noreferrer" href="${geo}">Cómo llegar</a>`:''}</div>${r.fuentes?.length?`<div class="sources"><b>Fuentes</b><div>${r.fuentes.map(s=>safeUrl(s.url)?`<a href="${safeUrl(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.nombre.replace(/_/g,' '))}</a>`:'').join('')}</div></div>`:''}`;$('#ficha').hidden=false;const shade=document.createElement('div');shade.className='modal-shade';shade.onclick=closeRace;document.body.append(shade);$('#ficha .ficha-cerrar').onclick=closeRace;const u=new URL(location.href);u.searchParams.set('carrera',r.id);history.replaceState(null,'',u);}
function switchView(v){view=v;$('#tab-buscar').classList.toggle('on',v==='buscar');$('#tab-mapa').classList.toggle('on',v==='mapa');$('#tab-buscar').toggleAttribute('aria-current',v==='buscar');$('#tab-mapa').toggleAttribute('aria-current',v==='mapa');$('#hero').hidden=v!=='buscar';$('#results').className=v==='buscar'?'results':'map-layout';redraw();if(v==='mapa')setTimeout(()=>{map.invalidateSize();map.fitBounds([[27.5,-18.5],[44.5,4.5]],{padding:[20,20],maxZoom:7})},80)}
function regions(){const cc=[...new Set(carreras.map(r=>r.ccaa).filter(Boolean))].sort();$('#f-ccaa').innerHTML='<option value="">Toda España</option>'+cc.map(x=>`<option>${esc(x)}</option>`).join('');provinces();const ms=[...new Set(carreras.map(r=>r.fecha.slice(0,7)))].sort();$('#f-mes').innerHTML='<option value="">Cualquier mes</option>'+ms.map(x=>`<option value="${x}">${new Date(x+'-01T12:00:00').toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</option>`).join('')}
function provinces(){const p=[...new Set(carreras.filter(r=>!state.ccaa||r.ccaa===state.ccaa).map(r=>r.provincia).filter(Boolean))].sort();$('#f-provincia').innerHTML='<option value="">Todas</option>'+p.map(x=>`<option>${esc(x)}</option>`).join('');$('#f-provincia').value=state.province}
function clear(){Object.assign(state,{text:'',mod:'',ccaa:'',province:'',month:'',level:'',sort:'fecha',visibleOnly:false});$('#f-texto').value='';$('#map-search').value='';for(const id of ['f-ccaa','f-provincia','f-mes','f-nivel'])$('#'+id).value='';$('#f-orden').value='fecha';$('#solo-mapa').checked=false;$('#f-modalidad button.on')?.classList.remove('on');$('#f-modalidad button[data-v=""]').classList.add('on');visibleCount=30;redraw()}
function init(){map=L.map('mapa',{zoomControl:false}).setView([40,-3.5],6);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}',{attribution:'Esri, HERE, Garmin &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:16}).addTo(map);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer/tile/{z}/{y}/{x}',{maxZoom:16}).addTo(map);layer=L.layerGroup().addTo(map);map.on('moveend',()=>{if(state.visibleOnly&&view==='mapa')redraw()});fetch('data/races.json').then(r=>r.json()).then(d=>{carreras=d.carreras;regions();bind();$('#stats').textContent=`${carreras.length} carreras en el catálogo · Base: 16 sept · Fuentes revisadas el 25 sept`;redraw();const pts=carreras.filter(r=>r.lat&&r.lng).map(r=>[r.lat,r.lng]);if(pts.length){setTimeout(()=>{map.invalidateSize();map.fitBounds(pts,{padding:[20,20],maxZoom:7})},150)};const id=new URLSearchParams(location.search).get('carrera');if(id)openRace(carreras.find(r=>r.id===id))}).catch(err=>{console.error(err);$('#contador').textContent='No se pudo cargar el calendario.'})}
function bind(){$('#tab-buscar').onclick=()=>switchView('buscar');$('#tab-mapa').onclick=()=>switchView('mapa');$('#buscar-go').onclick=()=>$('#results').scrollIntoView({behavior:'smooth'});$('#f-toggle').onclick=()=>{const el=$('#advanced');el.hidden=!el.hidden;$('#f-toggle').textContent=el.hidden?'Filtros +':'Filtros −';$('#f-toggle').setAttribute('aria-expanded',!el.hidden)};$('#f-modalidad').onclick=e=>{const b=e.target.closest('button[data-v]');if(!b)return;$('#f-modalidad button.on')?.classList.remove('on');b.classList.add('on');state.mod=b.dataset.v;visibleCount=30;redraw()};for(const id of ['f-texto','map-search'])$('#'+id).oninput=e=>{state.text=e.target.value;$(id==='f-texto'?'#map-search':'#f-texto').value=state.text;visibleCount=30;redraw()};$('#f-ccaa').onchange=e=>{state.ccaa=e.target.value;state.province='';provinces();redraw()};for(const [id,key] of [['f-provincia','province'],['f-mes','month'],['f-nivel','level']])$('#'+id).onchange=e=>{state[key]=e.target.value;redraw()};$('#f-orden').onchange=e=>{state.sort=e.target.value;redraw()};$('#solo-mapa').onchange=e=>{state.visibleOnly=e.target.checked;redraw()};$('#limpiar').onclick=clear;$('#ver-mas').onclick=()=>{visibleCount+=30;redraw()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected)closeRace()})}
init();
